[deps]
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[extras]
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NPZ"]
